### ISSUE TITLE
Use with nRF52811

### ISSUE THREAD

**Issue by cat-arch** [xaionaro/stm32-enc28j60#3]
Hello,
Do you know if it is possible to use your code with Nordic chip nRF52811? (It's a ARMcortex-M4)

Thank you for your time and code 💯

**Comment by xaionaro** [comment]
Frankly, I do not do embedded for 3 years, already. And I do not know if it is possible to use the code with this chip.

And this is not really my code: I just took a code for Arduino and ported it for STM32, that's it :)

**Comment by cat-arch** [comment]
Thank you, anyway :)
